name: Continuous Delivery

on:
  push:
    branches: [main]

jobs:
  cicd:
    uses: trialstudio/reusable_github_workflows/.github/workflows/nodejs_static_site_container_cd.yml@main
    with:
      nodejs_version: 16.x
      build_directory: build
    secrets:
      github_repo_token: ${{ secrets.GITHUB_TOKEN }}
#  deploy_to_dev:
#    uses: trialstudio/reusable_github_workflows/.github/workflows/nodejs_deploy_to_s3.yml@main
#    needs: cicd
#    with:
#      release_tag: ${{ needs.cicd.outputs.release_tag }}
#      bucket: dev.demo-react-app.trial.studio
#    secrets:
#      AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_REACT_APP_AWS_ACCESS_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_REACT_APP_AWS_SECRET }}
#      AWS_DEFAULT_REGION: 'us-east-2'
