name: Continuous Delivery

on:
  push:
    branches: [main]
    paths-ignore:
      - .github

jobs:
  cicd:
    uses: trialstudio/reusable_github_workflows/.github/workflows/nodejs_static_site_container_cd.yml@main
    with:
      nodejs_version: 16.x
      build_directory: build
    secrets:
      github_repo_token: ${{ secrets.GITHUB_TOKEN }}
      aws_assume_role: ${{ secrets.AWS_ASSUME_ROLE }}
  deploy_to_dev:
    uses: trialstudio/reusable_github_workflows/.github/workflows/update_argo_app_config.yml@main
    with:
      app_name: svelte-test
      version: ${{ needs.cicd.outputs.release_tag }}
      environment: dev
      deployment_type: static-site
    secrets:
      gh_repo_write: ${{ secrets.GH_REPO_WRITE }}
