name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version of release to deploy which is usually the github tag.

jobs:
  deploy_to_dev:
    uses: trialstudio/reusable_github_workflows/.github/workflows/update_argo_app_config.yml@main
    with:
      app_name: svelte-test
      version: ${{ github.event.inputs.version }}
      environment: prod
      deployment_type: static-site
    secrets:
      gh_repo_write: ${{ secrets.GH_REPO_WRITE }}
