name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version of release to deploy which is usually the github tag.

jobs:
  deploy_to_dev:
    uses: trialstudio/reusable_github_workflows/.github/workflows/update_argo_app_config.yml@main
    with:
      APPLICATION_NAME: svelte-test
      VERSION: ${{ github.event.inputs.version }}
      ENVIRONMENT: dev
      DEPLOYMENT_TYPE: static-site
    secrets:
      GH_REPO_WRITE: ${{ secrets.GH_REPO_WRITE }}
