name: Pull Request Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: trialstudio/reusable_github_workflows/.github/workflows/nodejs_pull_request_check.yml@main
    with:
      nodejs_version: 16.x
